### ISSUE TITLE
scrypt, update block, bad password 

### ISSUE THREAD

**Issue by Findblocks** [xavatar/yiimp_install_scrypt#12]
scrypt, update block, bad password   i have never had that error before and the pools still finding blocks ?

https://prnt.sc/li1ogz

pools still finding blocks and ive never had this issue before , 

Just recently changed servers to a more powerfull server thats all 

thanks guys

**Comment by cryptopool-builders** [comment]
means the password you are using in your algo.conf files and the password blocknotify was built with are not the same

**Comment by xavatar** [comment]
Old => Close
