### ISSUE TITLE
not able to access admin panel

### ISSUE THREAD

**Issue by AnythingLinux** [xavatar/yiimp_install_scrypt#18]
i have used this script and did all as says but not able to access admin it shows a white page
![Screenshot from 2019-09-10 20-13-02](https://user-images.githubusercontent.com/1058663/64621388-6839f880-d407-11e9-885e-acfc2a9cca3c.png)

**Comment by ytconvertermp3** [comment]
I got the same problem. Did you fixed it ?

**Comment by AnythingLinux** [comment]
@ytconvertermp3 no not yet

**Comment by ytconvertermp3** [comment]
okay so i got it solved. it was a pretty easy solution. 
in the documentation is states 

> go to /var/web/serverconfig.php : update this file to include your public ip (line = YAAMP_ADMIN_IP) 

in stead of your public ip try your ip4 adress. You can change it by 
`sudo nano /var/web/serverconfig.php`

**Comment by AnythingLinux** [comment]
@ytconvertermp3 yes i did it but not work. my public ip address is: http://71.202.93.177/ and during setup i use /site/admin to show admin dashboard but not work.
  
![Screenshot from 2019-09-15 00-59-31](https://user-images.githubusercontent.com/1058663/64912651-26d18200-d754-11e9-97ba-dbe6f5041537.png)

**Comment by xavatar** [comment]
It's written in the readme or Wiki (https://github.com/xavatar/yiimp_install_scrypt/wiki) : 

YOU MUST UPDATE THE FOLLOWING FILES :

    /var/web/serverconfig.php : update this file to include your public ip (line = YAAMP_ADMIN_IP) to access the admin panel (Put your PERSONNAL IP, NOT IP of your VPS). update with public keys from exchanges. update with other information specific to your server..

**Comment by LinuxDevSecOps** [comment]
![YIIMP](https://user-images.githubusercontent.com/48767068/65370089-0420fb00-dc77-11e9-9bad-7d786c3c333a.PNG)

I am also facing same problem.
I updated public ip and also applied second solution from this link https://github.com/xavatar/yiimp_install_scrypt/wiki

But not solved. It admin panel returning a blank page. Please advice

**Comment by Tech1k** [comment]
I know this is an old and closed issue, but @LinuxDevSecOps have you tried navigating to '/site/common' or '/site/adminpanel'?

That was my issue. I couldn't access my dashboard without going to /site/adminpanel.

**Comment by ZippyStar13** [comment]
> I know this is an old and closed issue, but @LinuxDevSecOps have you tried navigating to '/site/common' or '/site/adminpanel'?
> 
> That was my issue. I couldn't access my dashboard without going to /site/adminpanel.

Thank you for this!!  I was stumped.  I appreciate the help!
