### ISSUE TITLE
Error: unknown mnemonic

### ISSUE THREAD

**Issue by exbit** [xavatar/yiimp_install_scrypt#2]
gcc -g -march=native -DNO_EXCHANGE -DHAVE_CURL `mysql_config --cflags --libs` -c coind_template.cpp
/tmp/ccgydp9u.s: Assembler messages:
/tmp/ccgydp9u.s:63: Error: unknown mnemonic `bswapl' -- `bswapl x0'
Makefile:49: recipe for target 'coind_template.o' failed
make: *** [coind_template.o] Error 1

**Comment by xavatar** [comment]
I provide help only on Yiimp installation, not on installation or coin compilation.

**Comment by exbit** [comment]
this is a compilation of stratum for Yiimp

**Comment by xavatar** [comment]
You use this script on fresh ubuntu 16.04 Server ?
I tested now the script and i dont have error message, compilation of stratum is ok.

**Comment by exbit** [comment]
Yes. I use this script on fresh ubuntu 16.04 Server. As I understand it, the compilation error is only on the ARM architecture of the server processor.

**Comment by xavatar** [comment]
Oh ok, your server have a Arm Processor ?

**Comment by exbit** [comment]
Yes

**Comment by xavatar** [comment]
It's a raspberry ?

**Comment by exbit** [comment]
https://www.scaleway.com/virtual-cloud-servers/#anchor_arm

**Comment by xavatar** [comment]
I recovered a server with an ARM processor, I will be able to test.

**Comment by xavatar** [comment]
Confirmed, same error : 
gcc -g -march=native -DNO_EXCHANGE -DHAVE_CURL `mysql_config --cflags --libs` -c coind_template.cpp
/tmp/cco5nF1c.s: Assembler messages:
/tmp/cco5nF1c.s:132: Error: bad instruction `bswapl r3'
Makefile:49: recipe for target 'coind_template.o' failed
make: *** [coind_template.o] Error 1

**Comment by xavatar** [comment]
Old => Close
