### ISSUE TITLE
Installing php7.3

### ISSUE THREAD

**Issue by Marksmine** [xavatar/yiimp_install_scrypt#22]
Installed the scrypt many times before the update and worked flawless on 16.04 

the new scrypt the homepage dont load up and getting error php7.3-fpm.service

=> Installing php7.3 :

● php7.3-fpm.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

Any Ideas or where can i get the old scrypt from :) thasnks

**Comment by xavatar** [comment]
U can use this script install-debug.sh instead install.sh and u see the error during installation.
Old script are here : https://github.com/xavatar/yiimp_install_scrypt/tree/master/old
