### ISSUE TITLE
PHP Fatal error:  Cannot redeclare SiteController::actionAdmin()

### ISSUE THREAD

**Issue by valentino-sm** [xavatar/yiimp_install_scrypt#3]
All pages are empty after installing.

var/log/nginx/error.log contains this:

PHP Fatal error:  Cannot redeclare SiteController::actionAdmin() in /var/web/yaamp/modules/site/SiteController.php on line 571" while reading response header from upstream

**Comment by nikolai-git-house** [comment]
Yeah I also have same issue.
I setup yiimp mining pool following this guide.
When I visit site then its blank page. The nginx log says  above issue.
Please help,

**Comment by valentino-sm** [comment]
simba555,
I solved a problem.
Change file /var/web/yaamp/modules/site/SiteController.php to original from GitHub.

**Comment by xavatar** [comment]
All site are blank or just "Panel Admin" ?
If you change the file SiteController.php to original from GitHub, you must use "AdminRights" to access admin panel (like this : example.com/site/AdminRights)
