### ISSUE TITLE
Payment Failed when DO Payments are clicked

### ISSUE THREAD

**Issue by swatchie-1** [xavatar/yiimp_install_scrypt#5]
Hi Xavatar, any idea why Yiimp will not send payments to my miners? The balances are accumulated in the Pool's wallet but won't initiate payouts.

**Comment by Boumbacomputer** [comment]
Did you check to make sure you have enough coins in your pool wallet to pay for the tx fee? (other than the coins the miner won)

**Comment by ghost** [comment]
I've exactly the same problem here.
can't do any payments and i'm now not looking serious to my miners :/
I'm pretty sure i've enough coins to pay for the tx, i've even tried to do one payment at a time but it doesn't work for now :/

**Comment by 0xcitchx** [comment]
same issue

**Comment by Boumbacomputer** [comment]
Make sure you edit /var/web/yaamp/core/backend/payment.php and on line 57 you will need to add : $coin->symbol == 'XXX'

**Comment by FIRE-COOL** [comment]
yes, same issue, is already fixed? Thanks!

**Comment by morethz79** [comment]
Sorry ... I also have the same problem, I can not pay my miner. 
Do I have to send coins to the Master wallet of my pool?

what should I also enter on Charity Percent and Charity Address?

thank you

**Comment by xavatar** [comment]
https://github.com/xavatar/yiimp_install_scrypt/issues/5#issuecomment-422911431

Make sure you edit /var/web/yaamp/core/backend/payment.php and on line 57 you will need to add : $coin->symbol == 'XXX'

**Comment by usapool** [comment]
how do i fix this error -4: fee estimation failed. fallbackfee is disabled. wait a few blocks or enable -fallbackfee.
