### ISSUE TITLE
Adding new algos

### ISSUE THREAD

**Issue by ETS5** [xavatar/yiimp_install_scrypt#9]
So where is the yiimp file/folder we are suppose to update say we want to manually update the pool without wanting to run the install again. 

You have a have folder called install only do not run commands from this folder 

I need the stratum.h and stuff like that where did that go?

**Comment by ETS5** [comment]
So what i am saying say like this lbk3 algo that was just released normally you would do the following:
create the lbk3 .h file in stratum/algos/
create the lbk3.c file in stratum/algos/
then put lbk3.c in  /stratum/algos/makefile 
then create file lbk3.conf in /var/stratum/config
then add #include "algos/lbk3.h" in startum/stratum.h
You can if you want (recommended) tho to add it to the /web/yaamp/core/functions/yaamp.php

**Comment by xavatar** [comment]
Problem with Yiimp, not installer, please visit Discord.
Old => Close
